################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/animator/SkAnimateActive.cpp \
../src/animator/SkAnimateBase.cpp \
../src/animator/SkAnimateField.cpp \
../src/animator/SkAnimateMaker.cpp \
../src/animator/SkAnimateSet.cpp \
../src/animator/SkAnimator.cpp \
../src/animator/SkAnimatorScript.cpp \
../src/animator/SkAnimatorScript2.cpp \
../src/animator/SkBase64.cpp \
../src/animator/SkBoundable.cpp \
../src/animator/SkBuildCondensedInfo.cpp \
../src/animator/SkCondensedDebug.cpp \
../src/animator/SkCondensedRelease.cpp \
../src/animator/SkDisplayAdd.cpp \
../src/animator/SkDisplayApply.cpp \
../src/animator/SkDisplayBounds.cpp \
../src/animator/SkDisplayEvent.cpp \
../src/animator/SkDisplayEvents.cpp \
../src/animator/SkDisplayInclude.cpp \
../src/animator/SkDisplayInput.cpp \
../src/animator/SkDisplayList.cpp \
../src/animator/SkDisplayMath.cpp \
../src/animator/SkDisplayMovie.cpp \
../src/animator/SkDisplayNumber.cpp \
../src/animator/SkDisplayPost.cpp \
../src/animator/SkDisplayRandom.cpp \
../src/animator/SkDisplayScreenplay.cpp \
../src/animator/SkDisplayType.cpp \
../src/animator/SkDisplayTypes.cpp \
../src/animator/SkDisplayXMLParser.cpp \
../src/animator/SkDisplayable.cpp \
../src/animator/SkDraw3D.cpp \
../src/animator/SkDrawBitmap.cpp \
../src/animator/SkDrawBlur.cpp \
../src/animator/SkDrawClip.cpp \
../src/animator/SkDrawColor.cpp \
../src/animator/SkDrawDash.cpp \
../src/animator/SkDrawDiscrete.cpp \
../src/animator/SkDrawEmboss.cpp \
../src/animator/SkDrawExtraPathEffect.cpp \
../src/animator/SkDrawFull.cpp \
../src/animator/SkDrawGradient.cpp \
../src/animator/SkDrawGroup.cpp \
../src/animator/SkDrawLine.cpp \
../src/animator/SkDrawMatrix.cpp \
../src/animator/SkDrawOval.cpp \
../src/animator/SkDrawPaint.cpp \
../src/animator/SkDrawPath.cpp \
../src/animator/SkDrawPoint.cpp \
../src/animator/SkDrawRectangle.cpp \
../src/animator/SkDrawSaveLayer.cpp \
../src/animator/SkDrawShader.cpp \
../src/animator/SkDrawText.cpp \
../src/animator/SkDrawTextBox.cpp \
../src/animator/SkDrawTo.cpp \
../src/animator/SkDrawTransparentShader.cpp \
../src/animator/SkDrawable.cpp \
../src/animator/SkDump.cpp \
../src/animator/SkGetCondensedInfo.cpp \
../src/animator/SkHitClear.cpp \
../src/animator/SkHitTest.cpp \
../src/animator/SkMatrixParts.cpp \
../src/animator/SkMemberInfo.cpp \
../src/animator/SkOpArray.cpp \
../src/animator/SkOperandIterpolator.cpp \
../src/animator/SkPaintParts.cpp \
../src/animator/SkParseSVGPath.cpp \
../src/animator/SkPathParts.cpp \
../src/animator/SkPostParts.cpp \
../src/animator/SkScript.cpp \
../src/animator/SkScriptDecompile.cpp \
../src/animator/SkScriptRuntime.cpp \
../src/animator/SkScriptTokenizer.cpp \
../src/animator/SkSnapshot.cpp \
../src/animator/SkTextOnPath.cpp \
../src/animator/SkTextToPath.cpp \
../src/animator/SkTime.cpp \
../src/animator/SkTypedArray.cpp \
../src/animator/SkXMLAnimatorWriter.cpp 

OBJS += \
./src/animator/SkAnimateActive.o \
./src/animator/SkAnimateBase.o \
./src/animator/SkAnimateField.o \
./src/animator/SkAnimateMaker.o \
./src/animator/SkAnimateSet.o \
./src/animator/SkAnimator.o \
./src/animator/SkAnimatorScript.o \
./src/animator/SkAnimatorScript2.o \
./src/animator/SkBase64.o \
./src/animator/SkBoundable.o \
./src/animator/SkBuildCondensedInfo.o \
./src/animator/SkCondensedDebug.o \
./src/animator/SkCondensedRelease.o \
./src/animator/SkDisplayAdd.o \
./src/animator/SkDisplayApply.o \
./src/animator/SkDisplayBounds.o \
./src/animator/SkDisplayEvent.o \
./src/animator/SkDisplayEvents.o \
./src/animator/SkDisplayInclude.o \
./src/animator/SkDisplayInput.o \
./src/animator/SkDisplayList.o \
./src/animator/SkDisplayMath.o \
./src/animator/SkDisplayMovie.o \
./src/animator/SkDisplayNumber.o \
./src/animator/SkDisplayPost.o \
./src/animator/SkDisplayRandom.o \
./src/animator/SkDisplayScreenplay.o \
./src/animator/SkDisplayType.o \
./src/animator/SkDisplayTypes.o \
./src/animator/SkDisplayXMLParser.o \
./src/animator/SkDisplayable.o \
./src/animator/SkDraw3D.o \
./src/animator/SkDrawBitmap.o \
./src/animator/SkDrawBlur.o \
./src/animator/SkDrawClip.o \
./src/animator/SkDrawColor.o \
./src/animator/SkDrawDash.o \
./src/animator/SkDrawDiscrete.o \
./src/animator/SkDrawEmboss.o \
./src/animator/SkDrawExtraPathEffect.o \
./src/animator/SkDrawFull.o \
./src/animator/SkDrawGradient.o \
./src/animator/SkDrawGroup.o \
./src/animator/SkDrawLine.o \
./src/animator/SkDrawMatrix.o \
./src/animator/SkDrawOval.o \
./src/animator/SkDrawPaint.o \
./src/animator/SkDrawPath.o \
./src/animator/SkDrawPoint.o \
./src/animator/SkDrawRectangle.o \
./src/animator/SkDrawSaveLayer.o \
./src/animator/SkDrawShader.o \
./src/animator/SkDrawText.o \
./src/animator/SkDrawTextBox.o \
./src/animator/SkDrawTo.o \
./src/animator/SkDrawTransparentShader.o \
./src/animator/SkDrawable.o \
./src/animator/SkDump.o \
./src/animator/SkGetCondensedInfo.o \
./src/animator/SkHitClear.o \
./src/animator/SkHitTest.o \
./src/animator/SkMatrixParts.o \
./src/animator/SkMemberInfo.o \
./src/animator/SkOpArray.o \
./src/animator/SkOperandIterpolator.o \
./src/animator/SkPaintParts.o \
./src/animator/SkParseSVGPath.o \
./src/animator/SkPathParts.o \
./src/animator/SkPostParts.o \
./src/animator/SkScript.o \
./src/animator/SkScriptDecompile.o \
./src/animator/SkScriptRuntime.o \
./src/animator/SkScriptTokenizer.o \
./src/animator/SkSnapshot.o \
./src/animator/SkTextOnPath.o \
./src/animator/SkTextToPath.o \
./src/animator/SkTime.o \
./src/animator/SkTypedArray.o \
./src/animator/SkXMLAnimatorWriter.o 

CPP_DEPS += \
./src/animator/SkAnimateActive.d \
./src/animator/SkAnimateBase.d \
./src/animator/SkAnimateField.d \
./src/animator/SkAnimateMaker.d \
./src/animator/SkAnimateSet.d \
./src/animator/SkAnimator.d \
./src/animator/SkAnimatorScript.d \
./src/animator/SkAnimatorScript2.d \
./src/animator/SkBase64.d \
./src/animator/SkBoundable.d \
./src/animator/SkBuildCondensedInfo.d \
./src/animator/SkCondensedDebug.d \
./src/animator/SkCondensedRelease.d \
./src/animator/SkDisplayAdd.d \
./src/animator/SkDisplayApply.d \
./src/animator/SkDisplayBounds.d \
./src/animator/SkDisplayEvent.d \
./src/animator/SkDisplayEvents.d \
./src/animator/SkDisplayInclude.d \
./src/animator/SkDisplayInput.d \
./src/animator/SkDisplayList.d \
./src/animator/SkDisplayMath.d \
./src/animator/SkDisplayMovie.d \
./src/animator/SkDisplayNumber.d \
./src/animator/SkDisplayPost.d \
./src/animator/SkDisplayRandom.d \
./src/animator/SkDisplayScreenplay.d \
./src/animator/SkDisplayType.d \
./src/animator/SkDisplayTypes.d \
./src/animator/SkDisplayXMLParser.d \
./src/animator/SkDisplayable.d \
./src/animator/SkDraw3D.d \
./src/animator/SkDrawBitmap.d \
./src/animator/SkDrawBlur.d \
./src/animator/SkDrawClip.d \
./src/animator/SkDrawColor.d \
./src/animator/SkDrawDash.d \
./src/animator/SkDrawDiscrete.d \
./src/animator/SkDrawEmboss.d \
./src/animator/SkDrawExtraPathEffect.d \
./src/animator/SkDrawFull.d \
./src/animator/SkDrawGradient.d \
./src/animator/SkDrawGroup.d \
./src/animator/SkDrawLine.d \
./src/animator/SkDrawMatrix.d \
./src/animator/SkDrawOval.d \
./src/animator/SkDrawPaint.d \
./src/animator/SkDrawPath.d \
./src/animator/SkDrawPoint.d \
./src/animator/SkDrawRectangle.d \
./src/animator/SkDrawSaveLayer.d \
./src/animator/SkDrawShader.d \
./src/animator/SkDrawText.d \
./src/animator/SkDrawTextBox.d \
./src/animator/SkDrawTo.d \
./src/animator/SkDrawTransparentShader.d \
./src/animator/SkDrawable.d \
./src/animator/SkDump.d \
./src/animator/SkGetCondensedInfo.d \
./src/animator/SkHitClear.d \
./src/animator/SkHitTest.d \
./src/animator/SkMatrixParts.d \
./src/animator/SkMemberInfo.d \
./src/animator/SkOpArray.d \
./src/animator/SkOperandIterpolator.d \
./src/animator/SkPaintParts.d \
./src/animator/SkParseSVGPath.d \
./src/animator/SkPathParts.d \
./src/animator/SkPostParts.d \
./src/animator/SkScript.d \
./src/animator/SkScriptDecompile.d \
./src/animator/SkScriptRuntime.d \
./src/animator/SkScriptTokenizer.d \
./src/animator/SkSnapshot.d \
./src/animator/SkTextOnPath.d \
./src/animator/SkTextToPath.d \
./src/animator/SkTime.d \
./src/animator/SkTypedArray.d \
./src/animator/SkXMLAnimatorWriter.d 


# Each subdirectory must supply rules for building sources it contributes
src/animator/%.o: ../src/animator/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


