################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../samplecode/ClockFaceView.cpp \
../samplecode/OverView.cpp \
../samplecode/SampleAll.cpp \
../samplecode/SampleAnimator.cpp \
../samplecode/SampleApp.cpp \
../samplecode/SampleArc.cpp \
../samplecode/SampleAvoid.cpp \
../samplecode/SampleBigGradient.cpp \
../samplecode/SampleBitmapRect.cpp \
../samplecode/SampleBlur.cpp \
../samplecode/SampleCamera.cpp \
../samplecode/SampleCircle.cpp \
../samplecode/SampleComplexClip.cpp \
../samplecode/SampleCull.cpp \
../samplecode/SampleDecode.cpp \
../samplecode/SampleDither.cpp \
../samplecode/SampleDitherBitmap.cpp \
../samplecode/SampleDraw.cpp \
../samplecode/SampleDrawLooper.cpp \
../samplecode/SampleEffects.cpp \
../samplecode/SampleEmboss.cpp \
../samplecode/SampleEncode.cpp \
../samplecode/SampleExtractAlpha.cpp \
../samplecode/SampleFillType.cpp \
../samplecode/SampleFilter.cpp \
../samplecode/SampleFilter2.cpp \
../samplecode/SampleFontCache.cpp \
../samplecode/SampleFontScalerTest.cpp \
../samplecode/SampleFuzz.cpp \
../samplecode/SampleGM.cpp \
../samplecode/SampleGradients.cpp \
../samplecode/SampleHairline.cpp \
../samplecode/SampleImage.cpp \
../samplecode/SampleImageDir.cpp \
../samplecode/SampleLCD.cpp \
../samplecode/SampleLayerMask.cpp \
../samplecode/SampleLayers.cpp \
../samplecode/SampleLineClipper.cpp \
../samplecode/SampleLines.cpp \
../samplecode/SampleMeasure.cpp \
../samplecode/SampleMipMap.cpp \
../samplecode/SampleMovie.cpp \
../samplecode/SampleNinePatch.cpp \
../samplecode/SampleOvalTest.cpp \
../samplecode/SampleOverflow.cpp \
../samplecode/SamplePageFlip.cpp \
../samplecode/SamplePatch.cpp \
../samplecode/SamplePath.cpp \
../samplecode/SamplePathClip.cpp \
../samplecode/SamplePathEffects.cpp \
../samplecode/SamplePicture.cpp \
../samplecode/SamplePoints.cpp \
../samplecode/SamplePolyToPoly.cpp \
../samplecode/SampleRegion.cpp \
../samplecode/SampleRepeatTile.cpp \
../samplecode/SampleSVG.cpp \
../samplecode/SampleShaderText.cpp \
../samplecode/SampleShaders.cpp \
../samplecode/SampleShapes.cpp \
../samplecode/SampleSkLayer.cpp \
../samplecode/SampleSlides.cpp \
../samplecode/SampleStrokePath.cpp \
../samplecode/SampleStrokeText.cpp \
../samplecode/SampleTestGL.cpp \
../samplecode/SampleTests.cpp \
../samplecode/SampleText.cpp \
../samplecode/SampleTextAlpha.cpp \
../samplecode/SampleTextBox.cpp \
../samplecode/SampleTextEffects.cpp \
../samplecode/SampleTextOnPath.cpp \
../samplecode/SampleTiling.cpp \
../samplecode/SampleTinyBitmap.cpp \
../samplecode/SampleTriangles.cpp \
../samplecode/SampleTypeface.cpp \
../samplecode/SampleUnitMapper.cpp \
../samplecode/SampleVertices.cpp \
../samplecode/SampleWarp.cpp \
../samplecode/SampleXfermodes.cpp \
../samplecode/vertexdump.cpp 

OBJS += \
./samplecode/ClockFaceView.o \
./samplecode/OverView.o \
./samplecode/SampleAll.o \
./samplecode/SampleAnimator.o \
./samplecode/SampleApp.o \
./samplecode/SampleArc.o \
./samplecode/SampleAvoid.o \
./samplecode/SampleBigGradient.o \
./samplecode/SampleBitmapRect.o \
./samplecode/SampleBlur.o \
./samplecode/SampleCamera.o \
./samplecode/SampleCircle.o \
./samplecode/SampleComplexClip.o \
./samplecode/SampleCull.o \
./samplecode/SampleDecode.o \
./samplecode/SampleDither.o \
./samplecode/SampleDitherBitmap.o \
./samplecode/SampleDraw.o \
./samplecode/SampleDrawLooper.o \
./samplecode/SampleEffects.o \
./samplecode/SampleEmboss.o \
./samplecode/SampleEncode.o \
./samplecode/SampleExtractAlpha.o \
./samplecode/SampleFillType.o \
./samplecode/SampleFilter.o \
./samplecode/SampleFilter2.o \
./samplecode/SampleFontCache.o \
./samplecode/SampleFontScalerTest.o \
./samplecode/SampleFuzz.o \
./samplecode/SampleGM.o \
./samplecode/SampleGradients.o \
./samplecode/SampleHairline.o \
./samplecode/SampleImage.o \
./samplecode/SampleImageDir.o \
./samplecode/SampleLCD.o \
./samplecode/SampleLayerMask.o \
./samplecode/SampleLayers.o \
./samplecode/SampleLineClipper.o \
./samplecode/SampleLines.o \
./samplecode/SampleMeasure.o \
./samplecode/SampleMipMap.o \
./samplecode/SampleMovie.o \
./samplecode/SampleNinePatch.o \
./samplecode/SampleOvalTest.o \
./samplecode/SampleOverflow.o \
./samplecode/SamplePageFlip.o \
./samplecode/SamplePatch.o \
./samplecode/SamplePath.o \
./samplecode/SamplePathClip.o \
./samplecode/SamplePathEffects.o \
./samplecode/SamplePicture.o \
./samplecode/SamplePoints.o \
./samplecode/SamplePolyToPoly.o \
./samplecode/SampleRegion.o \
./samplecode/SampleRepeatTile.o \
./samplecode/SampleSVG.o \
./samplecode/SampleShaderText.o \
./samplecode/SampleShaders.o \
./samplecode/SampleShapes.o \
./samplecode/SampleSkLayer.o \
./samplecode/SampleSlides.o \
./samplecode/SampleStrokePath.o \
./samplecode/SampleStrokeText.o \
./samplecode/SampleTestGL.o \
./samplecode/SampleTests.o \
./samplecode/SampleText.o \
./samplecode/SampleTextAlpha.o \
./samplecode/SampleTextBox.o \
./samplecode/SampleTextEffects.o \
./samplecode/SampleTextOnPath.o \
./samplecode/SampleTiling.o \
./samplecode/SampleTinyBitmap.o \
./samplecode/SampleTriangles.o \
./samplecode/SampleTypeface.o \
./samplecode/SampleUnitMapper.o \
./samplecode/SampleVertices.o \
./samplecode/SampleWarp.o \
./samplecode/SampleXfermodes.o \
./samplecode/vertexdump.o 

CPP_DEPS += \
./samplecode/ClockFaceView.d \
./samplecode/OverView.d \
./samplecode/SampleAll.d \
./samplecode/SampleAnimator.d \
./samplecode/SampleApp.d \
./samplecode/SampleArc.d \
./samplecode/SampleAvoid.d \
./samplecode/SampleBigGradient.d \
./samplecode/SampleBitmapRect.d \
./samplecode/SampleBlur.d \
./samplecode/SampleCamera.d \
./samplecode/SampleCircle.d \
./samplecode/SampleComplexClip.d \
./samplecode/SampleCull.d \
./samplecode/SampleDecode.d \
./samplecode/SampleDither.d \
./samplecode/SampleDitherBitmap.d \
./samplecode/SampleDraw.d \
./samplecode/SampleDrawLooper.d \
./samplecode/SampleEffects.d \
./samplecode/SampleEmboss.d \
./samplecode/SampleEncode.d \
./samplecode/SampleExtractAlpha.d \
./samplecode/SampleFillType.d \
./samplecode/SampleFilter.d \
./samplecode/SampleFilter2.d \
./samplecode/SampleFontCache.d \
./samplecode/SampleFontScalerTest.d \
./samplecode/SampleFuzz.d \
./samplecode/SampleGM.d \
./samplecode/SampleGradients.d \
./samplecode/SampleHairline.d \
./samplecode/SampleImage.d \
./samplecode/SampleImageDir.d \
./samplecode/SampleLCD.d \
./samplecode/SampleLayerMask.d \
./samplecode/SampleLayers.d \
./samplecode/SampleLineClipper.d \
./samplecode/SampleLines.d \
./samplecode/SampleMeasure.d \
./samplecode/SampleMipMap.d \
./samplecode/SampleMovie.d \
./samplecode/SampleNinePatch.d \
./samplecode/SampleOvalTest.d \
./samplecode/SampleOverflow.d \
./samplecode/SamplePageFlip.d \
./samplecode/SamplePatch.d \
./samplecode/SamplePath.d \
./samplecode/SamplePathClip.d \
./samplecode/SamplePathEffects.d \
./samplecode/SamplePicture.d \
./samplecode/SamplePoints.d \
./samplecode/SamplePolyToPoly.d \
./samplecode/SampleRegion.d \
./samplecode/SampleRepeatTile.d \
./samplecode/SampleSVG.d \
./samplecode/SampleShaderText.d \
./samplecode/SampleShaders.d \
./samplecode/SampleShapes.d \
./samplecode/SampleSkLayer.d \
./samplecode/SampleSlides.d \
./samplecode/SampleStrokePath.d \
./samplecode/SampleStrokeText.d \
./samplecode/SampleTestGL.d \
./samplecode/SampleTests.d \
./samplecode/SampleText.d \
./samplecode/SampleTextAlpha.d \
./samplecode/SampleTextBox.d \
./samplecode/SampleTextEffects.d \
./samplecode/SampleTextOnPath.d \
./samplecode/SampleTiling.d \
./samplecode/SampleTinyBitmap.d \
./samplecode/SampleTriangles.d \
./samplecode/SampleTypeface.d \
./samplecode/SampleUnitMapper.d \
./samplecode/SampleVertices.d \
./samplecode/SampleWarp.d \
./samplecode/SampleXfermodes.d \
./samplecode/vertexdump.d 


# Each subdirectory must supply rules for building sources it contributes
samplecode/%.o: ../samplecode/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


