################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/core/Sk64.cpp \
../src/core/SkAdvancedTypefaceMetrics.cpp \
../src/core/SkAlphaRuns.cpp \
../src/core/SkBitmap.cpp \
../src/core/SkBitmapProcShader.cpp \
../src/core/SkBitmapProcState.cpp \
../src/core/SkBitmapProcState_matrixProcs.cpp \
../src/core/SkBitmapSampler.cpp \
../src/core/SkBitmap_scroll.cpp \
../src/core/SkBlitRow_D16.cpp \
../src/core/SkBlitRow_D32.cpp \
../src/core/SkBlitRow_D4444.cpp \
../src/core/SkBlitter.cpp \
../src/core/SkBlitter_4444.cpp \
../src/core/SkBlitter_A1.cpp \
../src/core/SkBlitter_A8.cpp \
../src/core/SkBlitter_ARGB32.cpp \
../src/core/SkBlitter_ARGB32_Subpixel.cpp \
../src/core/SkBlitter_RGB16.cpp \
../src/core/SkBlitter_Sprite.cpp \
../src/core/SkBuffer.cpp \
../src/core/SkCanvas.cpp \
../src/core/SkChunkAlloc.cpp \
../src/core/SkClipStack.cpp \
../src/core/SkColor.cpp \
../src/core/SkColorFilter.cpp \
../src/core/SkColorTable.cpp \
../src/core/SkComposeShader.cpp \
../src/core/SkConcaveToTriangles.cpp \
../src/core/SkCordic.cpp \
../src/core/SkCubicClipper.cpp \
../src/core/SkDebug.cpp \
../src/core/SkDeque.cpp \
../src/core/SkDevice.cpp \
../src/core/SkDither.cpp \
../src/core/SkDraw.cpp \
../src/core/SkDrawing.cpp \
../src/core/SkEdge.cpp \
../src/core/SkEdgeBuilder.cpp \
../src/core/SkEdgeClipper.cpp \
../src/core/SkFilterProc.cpp \
../src/core/SkFlate.cpp \
../src/core/SkFlattenable.cpp \
../src/core/SkFloat.cpp \
../src/core/SkFloatBits.cpp \
../src/core/SkFontHost.cpp \
../src/core/SkGeometry.cpp \
../src/core/SkGlobals.cpp \
../src/core/SkGlyphCache.cpp \
../src/core/SkGraphics.cpp \
../src/core/SkLineClipper.cpp \
../src/core/SkMMapStream.cpp \
../src/core/SkMallocPixelRef.cpp \
../src/core/SkMask.cpp \
../src/core/SkMaskFilter.cpp \
../src/core/SkMath.cpp \
../src/core/SkMatrix.cpp \
../src/core/SkMemory_stdlib.cpp \
../src/core/SkMetaData.cpp \
../src/core/SkPackBits.cpp \
../src/core/SkPaint.cpp \
../src/core/SkPath.cpp \
../src/core/SkPathEffect.cpp \
../src/core/SkPathHeap.cpp \
../src/core/SkPathMeasure.cpp \
../src/core/SkPicture.cpp \
../src/core/SkPictureFlat.cpp \
../src/core/SkPicturePlayback.cpp \
../src/core/SkPictureRecord.cpp \
../src/core/SkPixelRef.cpp \
../src/core/SkPoint.cpp \
../src/core/SkProcSpriteBlitter.cpp \
../src/core/SkPtrRecorder.cpp \
../src/core/SkQuadClipper.cpp \
../src/core/SkRasterizer.cpp \
../src/core/SkRect.cpp \
../src/core/SkRefDict.cpp \
../src/core/SkRegion.cpp \
../src/core/SkRegion_path.cpp \
../src/core/SkRegion_rects.cpp \
../src/core/SkScalar.cpp \
../src/core/SkScalerContext.cpp \
../src/core/SkScan.cpp \
../src/core/SkScan_AntiPath.cpp \
../src/core/SkScan_Antihair.cpp \
../src/core/SkScan_Hairline.cpp \
../src/core/SkScan_Path.cpp \
../src/core/SkShader.cpp \
../src/core/SkShape.cpp \
../src/core/SkSpriteBlitter_ARGB32.cpp \
../src/core/SkSpriteBlitter_RGB16.cpp \
../src/core/SkStream.cpp \
../src/core/SkString.cpp \
../src/core/SkStroke.cpp \
../src/core/SkStrokerPriv.cpp \
../src/core/SkTSearch.cpp \
../src/core/SkTypeface.cpp \
../src/core/SkUnPreMultiply.cpp \
../src/core/SkUtils.cpp \
../src/core/SkWriter32.cpp \
../src/core/SkXfermode.cpp 

OBJS += \
./src/core/Sk64.o \
./src/core/SkAdvancedTypefaceMetrics.o \
./src/core/SkAlphaRuns.o \
./src/core/SkBitmap.o \
./src/core/SkBitmapProcShader.o \
./src/core/SkBitmapProcState.o \
./src/core/SkBitmapProcState_matrixProcs.o \
./src/core/SkBitmapSampler.o \
./src/core/SkBitmap_scroll.o \
./src/core/SkBlitRow_D16.o \
./src/core/SkBlitRow_D32.o \
./src/core/SkBlitRow_D4444.o \
./src/core/SkBlitter.o \
./src/core/SkBlitter_4444.o \
./src/core/SkBlitter_A1.o \
./src/core/SkBlitter_A8.o \
./src/core/SkBlitter_ARGB32.o \
./src/core/SkBlitter_ARGB32_Subpixel.o \
./src/core/SkBlitter_RGB16.o \
./src/core/SkBlitter_Sprite.o \
./src/core/SkBuffer.o \
./src/core/SkCanvas.o \
./src/core/SkChunkAlloc.o \
./src/core/SkClipStack.o \
./src/core/SkColor.o \
./src/core/SkColorFilter.o \
./src/core/SkColorTable.o \
./src/core/SkComposeShader.o \
./src/core/SkConcaveToTriangles.o \
./src/core/SkCordic.o \
./src/core/SkCubicClipper.o \
./src/core/SkDebug.o \
./src/core/SkDeque.o \
./src/core/SkDevice.o \
./src/core/SkDither.o \
./src/core/SkDraw.o \
./src/core/SkDrawing.o \
./src/core/SkEdge.o \
./src/core/SkEdgeBuilder.o \
./src/core/SkEdgeClipper.o \
./src/core/SkFilterProc.o \
./src/core/SkFlate.o \
./src/core/SkFlattenable.o \
./src/core/SkFloat.o \
./src/core/SkFloatBits.o \
./src/core/SkFontHost.o \
./src/core/SkGeometry.o \
./src/core/SkGlobals.o \
./src/core/SkGlyphCache.o \
./src/core/SkGraphics.o \
./src/core/SkLineClipper.o \
./src/core/SkMMapStream.o \
./src/core/SkMallocPixelRef.o \
./src/core/SkMask.o \
./src/core/SkMaskFilter.o \
./src/core/SkMath.o \
./src/core/SkMatrix.o \
./src/core/SkMemory_stdlib.o \
./src/core/SkMetaData.o \
./src/core/SkPackBits.o \
./src/core/SkPaint.o \
./src/core/SkPath.o \
./src/core/SkPathEffect.o \
./src/core/SkPathHeap.o \
./src/core/SkPathMeasure.o \
./src/core/SkPicture.o \
./src/core/SkPictureFlat.o \
./src/core/SkPicturePlayback.o \
./src/core/SkPictureRecord.o \
./src/core/SkPixelRef.o \
./src/core/SkPoint.o \
./src/core/SkProcSpriteBlitter.o \
./src/core/SkPtrRecorder.o \
./src/core/SkQuadClipper.o \
./src/core/SkRasterizer.o \
./src/core/SkRect.o \
./src/core/SkRefDict.o \
./src/core/SkRegion.o \
./src/core/SkRegion_path.o \
./src/core/SkRegion_rects.o \
./src/core/SkScalar.o \
./src/core/SkScalerContext.o \
./src/core/SkScan.o \
./src/core/SkScan_AntiPath.o \
./src/core/SkScan_Antihair.o \
./src/core/SkScan_Hairline.o \
./src/core/SkScan_Path.o \
./src/core/SkShader.o \
./src/core/SkShape.o \
./src/core/SkSpriteBlitter_ARGB32.o \
./src/core/SkSpriteBlitter_RGB16.o \
./src/core/SkStream.o \
./src/core/SkString.o \
./src/core/SkStroke.o \
./src/core/SkStrokerPriv.o \
./src/core/SkTSearch.o \
./src/core/SkTypeface.o \
./src/core/SkUnPreMultiply.o \
./src/core/SkUtils.o \
./src/core/SkWriter32.o \
./src/core/SkXfermode.o 

CPP_DEPS += \
./src/core/Sk64.d \
./src/core/SkAdvancedTypefaceMetrics.d \
./src/core/SkAlphaRuns.d \
./src/core/SkBitmap.d \
./src/core/SkBitmapProcShader.d \
./src/core/SkBitmapProcState.d \
./src/core/SkBitmapProcState_matrixProcs.d \
./src/core/SkBitmapSampler.d \
./src/core/SkBitmap_scroll.d \
./src/core/SkBlitRow_D16.d \
./src/core/SkBlitRow_D32.d \
./src/core/SkBlitRow_D4444.d \
./src/core/SkBlitter.d \
./src/core/SkBlitter_4444.d \
./src/core/SkBlitter_A1.d \
./src/core/SkBlitter_A8.d \
./src/core/SkBlitter_ARGB32.d \
./src/core/SkBlitter_ARGB32_Subpixel.d \
./src/core/SkBlitter_RGB16.d \
./src/core/SkBlitter_Sprite.d \
./src/core/SkBuffer.d \
./src/core/SkCanvas.d \
./src/core/SkChunkAlloc.d \
./src/core/SkClipStack.d \
./src/core/SkColor.d \
./src/core/SkColorFilter.d \
./src/core/SkColorTable.d \
./src/core/SkComposeShader.d \
./src/core/SkConcaveToTriangles.d \
./src/core/SkCordic.d \
./src/core/SkCubicClipper.d \
./src/core/SkDebug.d \
./src/core/SkDeque.d \
./src/core/SkDevice.d \
./src/core/SkDither.d \
./src/core/SkDraw.d \
./src/core/SkDrawing.d \
./src/core/SkEdge.d \
./src/core/SkEdgeBuilder.d \
./src/core/SkEdgeClipper.d \
./src/core/SkFilterProc.d \
./src/core/SkFlate.d \
./src/core/SkFlattenable.d \
./src/core/SkFloat.d \
./src/core/SkFloatBits.d \
./src/core/SkFontHost.d \
./src/core/SkGeometry.d \
./src/core/SkGlobals.d \
./src/core/SkGlyphCache.d \
./src/core/SkGraphics.d \
./src/core/SkLineClipper.d \
./src/core/SkMMapStream.d \
./src/core/SkMallocPixelRef.d \
./src/core/SkMask.d \
./src/core/SkMaskFilter.d \
./src/core/SkMath.d \
./src/core/SkMatrix.d \
./src/core/SkMemory_stdlib.d \
./src/core/SkMetaData.d \
./src/core/SkPackBits.d \
./src/core/SkPaint.d \
./src/core/SkPath.d \
./src/core/SkPathEffect.d \
./src/core/SkPathHeap.d \
./src/core/SkPathMeasure.d \
./src/core/SkPicture.d \
./src/core/SkPictureFlat.d \
./src/core/SkPicturePlayback.d \
./src/core/SkPictureRecord.d \
./src/core/SkPixelRef.d \
./src/core/SkPoint.d \
./src/core/SkProcSpriteBlitter.d \
./src/core/SkPtrRecorder.d \
./src/core/SkQuadClipper.d \
./src/core/SkRasterizer.d \
./src/core/SkRect.d \
./src/core/SkRefDict.d \
./src/core/SkRegion.d \
./src/core/SkRegion_path.d \
./src/core/SkRegion_rects.d \
./src/core/SkScalar.d \
./src/core/SkScalerContext.d \
./src/core/SkScan.d \
./src/core/SkScan_AntiPath.d \
./src/core/SkScan_Antihair.d \
./src/core/SkScan_Hairline.d \
./src/core/SkScan_Path.d \
./src/core/SkShader.d \
./src/core/SkShape.d \
./src/core/SkSpriteBlitter_ARGB32.d \
./src/core/SkSpriteBlitter_RGB16.d \
./src/core/SkStream.d \
./src/core/SkString.d \
./src/core/SkStroke.d \
./src/core/SkStrokerPriv.d \
./src/core/SkTSearch.d \
./src/core/SkTypeface.d \
./src/core/SkUnPreMultiply.d \
./src/core/SkUtils.d \
./src/core/SkWriter32.d \
./src/core/SkXfermode.d 


# Each subdirectory must supply rules for building sources it contributes
src/core/%.o: ../src/core/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


